name: Docker Image CI

on:
  push:
    branches:
      - main
      - v1
      - v2

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Set the Docker image tag based on the branch
      - name: Set up image tag
        id: set_image_tag
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "IMAGE_TAG=hermesheik/library-app:latest" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/v1" ]]; then
            echo "IMAGE_TAG=hermesheik/library-app:v1" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/v2" ]]; then
            echo "IMAGE_TAG=hermesheik/library-app:v2" >> $GITHUB_ENV
          else
            echo "IMAGE_TAG=hermesheik/library-app:dev" >> $GITHUB_ENV  # Default for other branches
          fi

      # Step 4: Build the Docker image
      - name: Build Docker image
        run: docker build . --file Dockerfile --tag ${{ env.IMAGE_TAG }}

      # Step 5: Push the Docker image to Docker Hub
      - name: Push Docker image
        run: docker push ${{ env.IMAGE_TAG }}
